name: Agent
on:
  workflow_call:
jobs:
  agent:
    env:
      DOCKER: false
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v1
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.5'
      - run: just test
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest && just lint
        if: ${{ matrix.runner == 'ubuntu-latest' }}
