name: Agent
on:
  workflow_call:
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-tags: true
      - uses: ./.github/actions/setup
      - run: just lint
      - run: just test
