name: Archive
on:
  workflow_call:
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@v3
        with:
          name: bin
          path: bin
      - run: chmod -R +x ./bin
      - run: just archive
      - uses: actions/upload-artifact@v3
        id: upload
        with:
          name: archives
          path: archives/**/*
