name: Cypress-nightly
on:
  workflow_call:
jobs:
  native:
    env:
      FUZZBUCKET_SSH_KEY: ${{ secrets.FUZZBUCKET_SSH_KEY }}
      FUZZBUCKET_URL: ${{ secrets.FUZZBUCKET_URL }}
      FUZZBUCKET_CREDENTIALS: ${{ secrets.FUZZBUCKET_CREDENTIALS }}
      CI: true
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.3.0
      - name: quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.549

      - uses: actions/download-artifact@v4
        with:
          name: bin
          path: bin
      - uses: actions/checkout@v4
        with:
          ref: kg-publisher
          repository: rstudio/connect-content
          path: "test/content"
          sparse-checkout: bundles
          sparse-checkout-cone-mode: false
          token: ${{ secrets.CONNECT_PAT }}
      - name: Run on Ubuntu only
        run: sudo apt-get install libcurl4-openssl-dev
        if: matrix.runs-on == 'ubuntu-latest'
      - run: R -e 'install.packages("renv", repos="https://packagemanager.posit.co/cran/latest")'
      - run: chmod -R +x ./bin
      - run: echo "${FUZZBUCKET_SSH_KEY}" > test/bats/fuzzbucket-ssh-key && chmod 600 test/bats/fuzzbucket-ssh-key
      - run: just bats install
      - run: just bats test common
      - run: just bats test init
      - run: just bats test deploy
