name: Image
on:
  workflow_call:
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - id: get-tag
        run: echo "tag=$(just --evaluate _tag)" >> "$GITHUB_OUTPUT"
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/package/Dockerfile
          push: false
          tags: ${{ steps.get-tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
