name: Main
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  # Unit Tests
  agent:
    uses: ./.github/workflows/agent.yaml
  vscode:
    uses: ./.github/workflows/vscode.yaml

  # Build
  build:
    uses: ./.github/workflows/build.yaml
  archive:
    needs: build
    uses: ./.github/workflows/archive.yaml
  upload:
    needs:
      - archive
    uses: ./.github/workflows/upload.yaml
    secrets: inherit

  # Integration Tests
  bats:
    needs: build
    secrets: inherit
    uses: ./.github/workflows/bats.yaml

  vscode-ui:
    needs: build
    secrets: inherit
    uses: ./.github/workflows/vscode-ui.yaml
