name: Main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: image
        run: just image
      - name: lint
        run: just lint
      - name: build
        run: just build
      - name: post-build-lint
        run: just post-build-lint
      - name: test
        run: just test
      - uses: actions/upload-artifact@v3
        with:
          path: bin/