name: Nightly
on:
  schedule:
    - cron: "0 06 * * *"
  workflow_dispatch:

jobs:
  agent:
    uses: ./.github/workflows/agent.yaml
  web:
    uses: ./.github/workflows/web.yaml
  build:
    uses: ./.github/workflows/build.yaml
  bats:
    needs: build
    uses: ./.github/workflows/bats.yaml
  fuzzbucket:
    secrets: inherit
    uses: ./.github/workflows/fuzzbucket.yaml
  cypress-nightly:
    needs: [build, fuzzbucket]
    secrets: inherit
    uses: ./.github/workflows/contract.yaml

  # Extensions
  jupyterlab:
    uses: ./.github/workflows/jupyterlab.yaml
  positron:
    uses: ./.github/workflows/positron.yaml
