name: Nightly
on:
  schedule:
    - cron: "0 06 * * *"
  workflow_dispatch:
    inputs:
      job:
        description: "Select the job to run in contract.yaml"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - bats-tests
          - vscode-ui-tests
jobs:
  agent:
    uses: ./.github/workflows/agent.yaml
  build:
    uses: ./.github/workflows/build.yaml
  nightly:
    needs: [build]
    secrets: inherit
    uses: ./.github/workflows/contract.yaml
    with:
      job: ${{ github.event.inputs.job || 'all' }}
  cleanup:
    needs: nightly
    secrets: inherit
    uses: ./.github/workflows/cleanup.yaml
  package:
    needs: build
    uses: ./.github/workflows/package.yaml
  archive:
    needs: build
    uses: ./.github/workflows/archive.yaml
  upload:
    needs:
      - archive
      - package
    uses: ./.github/workflows/upload.yaml
    with:
      nightly: true
    secrets: inherit

  # Extensions
  vscode:
    uses: ./.github/workflows/vscode.yaml
