name: Nightly
on:
  schedule:
    - cron: "0 06 * * *"
  workflow_dispatch:

jobs:

  agent:
    uses: ./.github/workflows/agent.yaml
  web:
    uses: ./.github/workflows/web.yaml
  build:
    uses: ./.github/workflows/build.yaml
  contract-deps:
    strategy:
      fail-fast: false
      matrix:
        CONNECT_VERSION: [2022.08.0, 2024.02.0]
    secrets: inherit
    uses: ./.github/workflows/contract-deps.yaml
  nightly:
    needs: [build, contract-deps]
    secrets: inherit
    uses: ./.github/workflows/contract.yaml
  cleanup:
    needs: nightly
    secrets: inherit
    uses: ./.github/workflows/cleanup.yaml

  # Extensions
  jupyterlab:
    uses: ./.github/workflows/jupyterlab.yaml
  vscode:
    uses: ./.github/workflows/vscode.yaml
