name: Package
on:
  workflow_call:
jobs:
  vscode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: just vscode install
      - run: just vscode package
      - uses: actions/upload-artifact@v3
        id: upload
        with:
          name: packages
          path: packages/**/*
