name: Package
on:
  workflow_call:
jobs:
  vscode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@v4
        with:
          name: bin
          path: bin
      - run: chmod -R +x ./bin
      - run: just package
      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: dist
          path: dist/**/*

      - uses: actions/upload-artifact@v4
        id: upload-extensions
        with:
          name: extensions
          path: extensions/vscode/**/*
          retention-days: 1

      # - uses: actions/upload-artifact@v4
      #   id: upload-ext-bin
      #   with:
      #     name: ext-bin
      #     path: extensions/vscode/bin/*
      #     retention-days: 1

      # - uses: actions/upload-artifact@v4
      #   id: upload-node_modules
      #   with:
      #     name: node_modules
      #     path: extensions/vscode/node_modules/*
      #     retention-days: 1

      # - uses: actions/upload-artifact@v4
      #   id: upload-package-lock
      #   with:
      #     name: package-lock
      #     path: extensions/vscode/package-lock.json
      #     retention-days: 1
