name: Pull Request
on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_CACHE_FOLDER: work/web/test/cypress/.cache
      - name: build and test
        run: just
      - uses: actions/upload-artifact@v3
        with:
          path: bin/