name: Pull Request
on:
  pull_request

# A note on debugging a github step:
#   You can ssh into the github action environment and poke around by using
#   https://github.com/marketplace/actions/debugging-with-tmate
#   Use `limit-access-to-actor: true` so only you can ssh into the environment!
#  
#   For example, to debug a failure, append this to the jobs list within the failing step
#   - name: Setup tmate session
#     if: ${{ failure() }}
#     uses: mxschmitt/action-tmate@v3
#     with:
#       limit-access-to-actor: true
#

jobs:
  pr-code-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        run: just image
      - name: install dependencies
        run: just install
      - name: lint the source files
        run: just lint
      - name: build the CLI client and Web UX
        run: just build
      - name: lint the build dependent files
        run: just post-build-lint
      - name: run all tests
        run: just test
      - uses: actions/upload-artifact@v3
        with:
          path: bin/


  test-windows-client:
    runs-on: windows-latest
    needs: pr-code-validation
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/download-artifact@v3
        with:
          path: bin/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Windows Tests
        env:
          CLIENT: windows-latest
          # bats reads the load libraries from relative path only in Windows
          BATS_SUPPORT_LIB: ..\..\libs\bats-support\load.bash
          BATS_ASSERT_LIB: ..\..\libs\bats-assert\load
        shell: powershell
        run: |
          cp -r .\bin\artifact\* bin\
          chmod +x .\bin\*\*
          just bats-install
          $env:Path += ";$env:GITHUB_WORKSPACE\test\libs\bats-core\bin"
          $env:BINARY_PATH = "$env:GITHUB_WORKSPACE\bin\windows-amd64\connect-client"
          cd test
          just cli-client $env:CLIENT
          Start-Process -FilePath "$env:GITHUB_WORKSPACE\bin\artifact\windows-amd64\connect-client.exe" -ArgumentList "account-ui", "--listen=localhost:9999" -WindowStyle Hidden -RedirectStandardOutput ./win-out.txt
          just ../web/install
          just ../web/build
          just ../web/ci-e2e $env:CLIENT

  test-macos-client:
    runs-on: macos-latest
    needs: pr-code-validation
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/download-artifact@v3
        with:
          path: bin/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - uses: mxschmitt/action-tmate@v3
      #   with: 
      #     detached: true
      #     limit-access-to-actor: true
      - name: Run macos
        env:
          CLIENT: macos-latest
          BATS_SUPPORT_LIB: ${{ github.workspace }}/test/libs/bats-support/load
          BATS_ASSERT_LIB: ${{ github.workspace }}/test/libs/bats-assert/load
          BINARY_PATH: ${{ github.workspace }}/bin/artifact/darwin-amd64/connect-client
        run: |
          cp -r ./bin/artifact/* bin/ && chmod +x ./bin/*/*
          just test/bats-install
          PATH="$PATH:${{ github.workspace }}/test/libs/bats-core/bin"
          cd ${{ github.workspace }}/test
          just cli-client ${CLIENT}
          nohup $BINARY_PATH account-ui --listen=localhost:9000 < /dev/null & > /dev/null &
          sleep 5
          ps
          just ../web/install
          just ../web/build
          just ../web/ci-e2e ${CLIENT}

  test-linux-clients:
    runs-on: ubuntu-latest
    needs: pr-code-validation
    strategy:
      matrix:
        CLIENT:
          - linux-amd64
          - linux-arm64
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/download-artifact@v3
        with:
          path: bin/
      # these are required to run docker on amd64 and arm64 platforms
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Linux Tests
        env:
          CLIENT: "${{ matrix.CLIENT }}"
        run: |
          cp -r ./bin/artifact/* bin/ && chmod +x ./bin/*/*
          cd test
          just build ${CLIENT}
          just cli-client ${CLIENT}
          just ui-client ${CLIENT}
          just ../web/install && \
          just ../web/build && \
          just ../web/ci-e2e ${CLIENT}
