name: Pull Request
on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: just test
      - name: Build
        run: just build
      - uses: actions/upload-artifact@v3
        with:
          path: bin/
  test-macos_and_windows-clients:
    needs: build
    strategy:
      matrix:
        CLIENT: 
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.CLIENT }}
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/download-artifact@v3
        with:
          path: bin/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLIENT: "${{ matrix.CLIENT }}"
     
      - uses: mxschmitt/action-tmate@v3
        with: 
          detached: true
          limit-access-to-actor: true

      - name: Run MacOS and Windows Tests
        env:
          CLIENT: "${{ matrix.CLIENT }}"
          BATS_SUPPORT_LIB: load ${{ github.workspace }}/libs/bats-support/load
          BATS_ASSERT_LIB: load ${{ github.workspace }}/libs/bats-assert/load
          BIN_TYPE: ${{ env.CLIENT == 'macos-latest' && 'darwin-amd64' || 'windows-amd64' }}
          SET_PATH: ${{ env.CLIENT == 'macos-latest' && 'PATH=$PATH:${{ github.workspace }}/libs/bats-core/bin' || '$env:PATH +=:${{ github.workspace }}/libs/bats-core/bin' }}
          BINARY_PATH: ${{ github.workspace }}/bin/${BIN_TYPE}/connect-client
        run: |
          cp -r bin/artifact/* bin/ && chmod +x bin/*/*
          git clone --depth=1 https://github.com/bats-core/bats-core.git ${{ github.workspace }}/libs/bats-core
          cd ${{ github.workspace }}/libs/bats-core
          ./install.sh ${{ github.workspace }}/libs/bats-core/installation
          git clone --depth=1 https://github.com/ztombol/bats-support.git ${{ github.workspace }}/libs/bats-support
          git clone --depth=1 https://github.com/ztombol/bats-assert.git ${{ github.workspace }}/libs/bats-assert
          $SET_PATH
          cd ${{ github.workspace }}/test
          just run-client ${CLIENT}

  test-linux-clients:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        CLIENT:
          - linux-amd64
          - linux-arm64
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/download-artifact@v3
        with:
          path: bin/
      # these are required to run docker on amd64 and arm64 platforms
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Linux Tests
        env:
          CLIENT: "${{ matrix.CLIENT }}"
        run: |
          cp -r bin/artifact/* bin/ && chmod +x bin/*/*
          just test/build ${CLIENT}
          just test/run-client ${CLIENT}
