name: Pull Request
on:
  pull_request:
  push:
    branches:
      - tdstein/ci-fetch-performance
# concurrency:
#   group: ${{ github.head_ref || github.ref }}
#   cancel-in-progress: true
jobs:
  agent:
    uses: ./.github/workflows/agent.yaml
  extensions:
    uses: ./.github/workflows/extensions.yaml
  web:
    uses: ./.github/workflows/web.yaml
  build:
    uses: ./.github/workflows/build.yaml
  bats:
    needs: build
    uses: ./.github/workflows/bats.yaml
  cypress:
    needs: build
    uses: ./.github/workflows/cypress.yaml
