# A note on debugging a github step:
#   You can ssh into the github action environment and poke around by using
#   https://github.com/marketplace/actions/debugging-with-tmate
#   Use `limit-access-to-actor: true` so only you can ssh into the environment!
#  
#   For example, add this to the jobs list near the end
# - name: Setup tmate session
#   if: ${{ failure() }}
#   uses: mxschmitt/action-tmate@v3
#   with:
#     limit-access-to-actor: true
#

name: Pull Request
on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build and test
        run: just
        env:
          CYPRESS_CACHE_FOLDER: /work/web/test/cypress/.cache
      - uses: actions/upload-artifact@v3
        with:
          path: bin/
