name: Pull Request
on:
  pull_request:
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  agent:
    uses: ./.github/workflows/agent.yaml
  web:
    uses: ./.github/workflows/web.yaml
  build:
    uses: ./.github/workflows/build.yaml
  bats:
    needs: build
    uses: ./.github/workflows/bats.yaml
  cypress:
    needs: build
    uses: ./.github/workflows/ui.yaml
  package:
    uses: ./.github/workflows/package.yaml

  # Extensions
  jupyterlab:
    uses: ./.github/workflows/jupyterlab.yaml
  vscode:
    uses: ./.github/workflows/vscode.yaml
