name: Release
on:
  push:
    branches:
      - tdstein/release
    tags:
      - "v*.*.*"
jobs:
  package:
    uses: ./.github/workflows/package.yaml
  release:
    runs-on: ubuntu-latest
    needs:
      - package
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: executables
          path: bin
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/**/*
