name: vscode-ui
on:
  workflow_call:
env:
  VSCODE_VERSION: stable
jobs:
  ui-tests:
    env:
      DOCKER_CONNECT: true
      CONNECT_LICENSE: ${{ secrets.CONNECT_LICENSE }}
      CI: true
      QUARTO_VERSION: 1.4.549
      PYTHON_VERSION: 3.12.4
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - uses: extractions/setup-just@v2

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      # disabling quarto until we need it
      # - uses: quarto-dev/quarto-actions/setup@v2
      #   with:
      #     version: ${{ env.QUARTO_VERSION }}

      - uses: t1m0thyj/unlock-keyring@v1

      - run: just vscode configure
      - run: just vscode-ui install
      - run: just vscode-ui build-connect
      - run: just vscode-ui test vscode-nested
        env:
          SPEC_PATH: ./test/specs/nested-fastapi.spec.ts
          WORKSPACE_PATH: ../sample-content/

      - uses: actions/upload-artifact@v4
        id: download
        with:
          name: vscode-extension
          path: extensions/vscode

      - name: Save screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.runs-on}}-webdriver-screenshots
          path: test/vscode-ui/errorShots
          if-no-files-found: ignore
          retention-days: 1
